name = "MimiPAGE2009"
uuid = "e25d4f70-4200-11e9-37f3-3b45f1cef54f"

[deps]
Mimi = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
ExcelReaders = "c04bee98-12a5-510c-87df-2a230cb6e075"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
