name = "MimiPAGE2009"
uuid = "e25d4f70-4200-11e9-37f3-3b45f1cef54f"
version = "4.1.1-DEV"

[deps]
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Mimi = "e4e893b0-ee5e-52ea-8111-44b3bdec128c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Query = "0.12, 1.0"
julia = "1.4"
Distributions = "0.20, 0.21, 0.22, 0.23, 0.24, 0.25"
CSVFiles = "0.16, 1"
DataFrames = "0.19.1, 0.20, 0.21, 0.22, 1.0"
Mimi = "1.3"

[targets]
test = ["Test"]
